### ISSUE TITLE
Ability to ignore a block in convertToHtml

### ISSUE THREAD

**Issue by jonzlin95** [HubSpot/draft-convert#59] opened 2017-04-11 22:09 UTC
Hi,

I couldn't figure out how to do this, but basically whenever a user creates a blank new line in the editor, I want to ignore the output (Block type = unstyled, text = ''), but I can't seem to change the block output to be null or ''. I've resorted to using <span style={{display:none}} /> for now, but would love to get rid of the hack.

Thanks!

**Comment by benbriggs** [comment] 2017-04-20 18:21
Depending on how many cases you want to cover you could do this a couple ways:

Most simply, a `blockToHTML` configuration like this should work well: 
```es6
blockToHTML: ({type, text}) => {
  if (type === 'unstyled' && text.length === 0) {
    return {
      start: '',
      end: ''
    };
  }
}
```

Alternatively you could define it alongside any custom output you have for other `unstyled` blocks:
```es6
blockToHTML: ({type, text}) => {
  if (type === 'unstyled' && text.length === 0) {
    return {
      element: <p />, // or whatever you want non-empty unstyled blocks to be
      empty: ''
    };
  }
}
```

If you wanted to do it for all block types you could just remove that part of the condition. Hope this helps!

**Comment by benbriggs** [comment] 2017-04-20 18:23
Another way to approach the problem is making a transformation to the contentState itself before you convert it, e.g. getting an array of blocks and `.filter()`ing out any empty blocks. I could imagine losing blocks in the serialization process being potentially confusing down the road. This might be what you're already doing now.

**Comment by benbriggs** [comment] 2017-04-27 17:39
Closing this since I think those examples should solve the issue, feel free to reopen with any followup questions!

**Closed by benbriggs** 2017-04-27 17:39 UTC

**Comment by jonzlin95** [comment] 2017-05-10 07:27
Thanks a lot Ben. Was exactly what I was looking for, and thanks for the great work on the library!
